### ISSUE TITLE
Implementing authentication

### ISSUE THREAD

**Issue by ohrok** [ohrok/actixweb-sqlx-sample#5]
## Overview
Develop user authentication functions using basic and bearer authentication.

## Todo 
- [x] Add a password column to the users table
- [x] Add a tokens table
- [x] Add a login handler
- [x] Protect routes
